# Numpy tutorial

Optimized tools for vector, matrix, and high-level array calculations

In [1]:
import numpy as np

Load the numpy package and name it 'np'.

## 1. Create array

In [2]:
# Create an array
arr = np.array([[7,8,9], [10,11,12]])  
print('Create an array')
print(arr)

# Create an array from list
ls = [[7,8,9], [10,11,12]]        
arr_from_ls = np.array(ls)
print('Create an array from list')
print(ls)

# Create an array filled with 0s
print('Create an array filled with 0s')
print(np.zeros((3,2)))

# Create an array filled with 1s
print('Create an array filled with 1s')
print(np.ones((3,2)))

# Create an Unit array
print('Create an Unit array')
print(np.eye(3))

# Create a digonal array
print('Create a digonal array')
print(np.diag([1,2,3]))

# Create an array using range
a = np.array(range(20)).reshape((4,5))
print('Create an array using range')
print(a)

Create an array
[[ 7  8  9]
 [10 11 12]]
Create an array from list
[[7, 8, 9], [10, 11, 12]]
Create an array filled with 0s
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Create an array filled with 1s
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Create an Unit array
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Create a digonal array
[[1 0 0]
 [0 2 0]
 [0 0 3]]
Create an array using range
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## 2. Array operations

Calculate by element

In [3]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print('x + y')
print(x + y)
print('x - y')
print(x - y)
print('x * y')
print(x * y)
print('x / y')
print(x / y)
print('x**2')
print(x**2)


x + y
[[ 6  8]
 [10 12]]
x - y
[[-4 -4]
 [-4 -4]]
x * y
[[ 5 12]
 [21 32]]
x / y
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
x**2
[[ 1  4]
 [ 9 16]]


## 3. Linear algebra

__Diagonal matrix: np.diag(x)__


In [4]:
x = np.arange(9).reshape(3, 3)
print('x')
print(x)
print('np.diag(x)')
print(np.diag(x))
print('np.diag(np.diag(x))')
print(np.diag(np.diag(x)))

x
[[0 1 2]
 [3 4 5]
 [6 7 8]]
np.diag(x)
[0 4 8]
np.diag(np.diag(x))
[[0 0 0]
 [0 4 0]
 [0 0 8]]


__Matrix product: np.dot(a, b)__

In [5]:
np.dot(x,x)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

__Transpose: np.transpose(x)__

In [6]:
np.transpose(x)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

__Trace: np.trace(x)__

In [7]:
np.trace(x)

12

__Matrix Determinant: np.linalg.det(x)__

In [8]:
d = np.array([[1, 2], [3, 4]])
np.linalg.det(d)

-2.0000000000000004

__Inverse of a matrix: np.linalg.inv(d)__

In [9]:
inv_d=np.linalg.inv(d)
print(inv_d)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
np.dot(d, inv_d)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

__Eigenvalue, Eigenvector: w, v = np.linalg.eig(x)__

In [11]:
w, v = np.linalg.eig(d)#w: the eigenvalues lambda, v: the corresponding eigenvectors, one eigenvector per column
print('eigenvalues')
print(w)
print('eigenvectors')
print(v)

eigenvalues
[-0.37228132  5.37228132]
eigenvectors
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


__Singular Value Decomposition: u, s, vh = np.linalg.svd(d)__

In [12]:
u, s, v_t = np.linalg.svd(d)
print('u')
print(u)
print('s')
print(s)
print('v_t')
print(v_t)

u
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
s
[5.4649857  0.36596619]
v_t
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [13]:
np.dot(np.dot(u,np.diag(s)),v_t)

array([[1., 2.],
       [3., 4.]])

__Solve a linear matrix equation: np.linalg.solve(coef, cons)__

We will solve the two simultaneous equations (x0, x1) using the np.linalg.solve (coef, cons) function.

\begin{cases}
4x0 + 3x1 = 23 \\
3x0 + 2x1 = 16
\end{cases}


In [14]:
coef = np.array([[4, 3], [3, 2]])
cons = np.array([23, 16])
sol=np.linalg.solve(coef, cons)
print(sol)

[2. 5.]


In [15]:
print('4x0+3x1 =',4*sol[0]+3*sol[1])
print('3x0+2x1 =',3*sol[0]+2*sol[1])

4x0+3x1 = 23.0
3x0+2x1 = 16.0


The system of equations can also be found using the inverse matrix.

In [16]:
sol2=np.dot(np.linalg.inv(coef),cons)
print(sol2)

[2. 5.]


In [1]:
from IPython.display import HTML
HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
Hidden code in <a href="javascript:code_toggle()">here</a>.''')

__Example__
1. Calculate the determinant of \begin{pmatrix} 2&2&0 \\ -2&1&1 \\ 3&0&1 \end{pmatrix}
2. Solve a system of equations
\begin{cases}
3x_1+2x_2+x_3 = 7 \\
x_1-x_2+3x_3 = 3\\
5x_1+4x_2-2x_3 = 1
\end{cases}

In [18]:
a = np.array([[2,2,0],[-2,1,1],[3,0,1]])
inv_a = np.linalg.inv(a)
print(inv_a)

[[ 0.08333333 -0.16666667  0.16666667]
 [ 0.41666667  0.16666667 -0.16666667]
 [-0.25        0.5         0.5       ]]


In [19]:
np.dot(a,inv_a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
coef=np.array([[3,2,3],[1,-1,3],[5,4,-2]])
cons=np.array(np.array([7,3,1]))
x1,x2,x3=np.linalg.solve(coef,cons)
print('x1: ',x1)
print('x2: ',x2)
print('x3: ',x3)

x1:  -0.41935483870967777
x2:  1.6129032258064522
x3:  1.67741935483871


In [21]:
y1,y2,y3=np.dot(np.linalg.inv(coef),cons)
print('y1: ',y1)
print('y2: ',y2)
print('y3: ',y3)

y1:  -0.41935483870967805
y2:  1.6129032258064522
y3:  1.6774193548387097
